/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ContextMockContract
  extends Truffle.Contract<ContextMockInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ContextMockInstance>;
}

export interface Data {
  name: "Data";
  args: {
    data: string;
    integerValue: BN;
    stringValue: string;
    0: string;
    1: BN;
    2: string;
  };
}

export interface Sender {
  name: "Sender";
  args: {
    sender: string;
    0: string;
  };
}

type AllEvents = Data | Sender;

export interface ContextMockInstance extends Truffle.ContractInstance {
  msgSender: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  msgData: {
    (
      integerValue: number | BN | string,
      stringValue: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      integerValue: number | BN | string,
      stringValue: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      integerValue: number | BN | string,
      stringValue: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      integerValue: number | BN | string,
      stringValue: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    msgSender: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    msgData: {
      (
        integerValue: number | BN | string,
        stringValue: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        integerValue: number | BN | string,
        stringValue: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        integerValue: number | BN | string,
        stringValue: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        integerValue: number | BN | string,
        stringValue: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
