/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IERC1155LoggerContract
  extends Truffle.Contract<IERC1155LoggerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IERC1155LoggerInstance>;
}

type AllEvents = never;

export interface IERC1155LoggerInstance extends Truffle.ContractInstance {
  offset: {
    (
      account: string,
      tokenId: number | BN | string,
      amount: number | BN | string,
      reason: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      account: string,
      tokenId: number | BN | string,
      amount: number | BN | string,
      reason: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      account: string,
      tokenId: number | BN | string,
      amount: number | BN | string,
      reason: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      account: string,
      tokenId: number | BN | string,
      amount: number | BN | string,
      reason: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    offset: {
      (
        account: string,
        tokenId: number | BN | string,
        amount: number | BN | string,
        reason: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        account: string,
        tokenId: number | BN | string,
        amount: number | BN | string,
        reason: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        account: string,
        tokenId: number | BN | string,
        amount: number | BN | string,
        reason: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        account: string,
        tokenId: number | BN | string,
        amount: number | BN | string,
        reason: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
