/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IERC20AdapterContract
  extends Truffle.Contract<IERC20AdapterInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IERC20AdapterInstance>;
}

type AllEvents = never;

export interface IERC20AdapterInstance extends Truffle.ContractInstance {
  /**
   * Initialize ERC20 contract
   */
  init: {
    (
      tokenId_: number | BN | string,
      name_: string,
      symbol_: string,
      decimals_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      tokenId_: number | BN | string,
      name_: string,
      symbol_: string,
      decimals_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      tokenId_: number | BN | string,
      name_: string,
      symbol_: string,
      decimals_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      tokenId_: number | BN | string,
      name_: string,
      symbol_: string,
      decimals_: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    /**
     * Initialize ERC20 contract
     */
    init: {
      (
        tokenId_: number | BN | string,
        name_: string,
        symbol_: string,
        decimals_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        tokenId_: number | BN | string,
        name_: string,
        symbol_: string,
        decimals_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        tokenId_: number | BN | string,
        name_: string,
        symbol_: string,
        decimals_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        tokenId_: number | BN | string,
        name_: string,
        symbol_: string,
        decimals_: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
