/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { AccessControlEnumerableContract } from "./AccessControlEnumerable";
import { AccessControlEnumerableMockContract } from "./AccessControlEnumerableMock";
import { AccessControlEnumerableStubContract } from "./AccessControlEnumerableStub";
import { AccessControlMockContract } from "./AccessControlMock";
import { AccessControlStubContract } from "./AccessControlStub";
import { ContextMockContract } from "./ContextMock";
import { ControllableContract } from "./Controllable";
import { ERC1155Contract } from "./ERC1155";
import { ERC1155BaseContract } from "./ERC1155Base";
import { ERC1155ERC20Contract } from "./ERC1155ERC20";
import { ERC1155OffsettableContract } from "./ERC1155Offsettable";
import { ERC1155PausableContract } from "./ERC1155Pausable";
import { ERC1155SupplyableContract } from "./ERC1155Supplyable";
import { ERC1155SwappableContract } from "./ERC1155Swappable";
import { ERC1155URIStorableContract } from "./ERC1155URIStorable";
import { ERC165Contract } from "./ERC165";
import { ERC165MockContract } from "./ERC165Mock";
import { ERC165StubContract } from "./ERC165Stub";
import { IAccessControlContract } from "./IAccessControl";
import { IAccessControlEnumerableContract } from "./IAccessControlEnumerable";
import { IERC1155Contract } from "./IERC1155";
import { IERC1155ERC20Contract } from "./IERC1155ERC20";
import { IERC1155HolderContract } from "./IERC1155Holder";
import { IERC1155LoggerContract } from "./IERC1155Logger";
import { IERC1155MetadataURIContract } from "./IERC1155MetadataURI";
import { IERC1155ReceiverContract } from "./IERC1155Receiver";
import { IERC1155SupplyableContract } from "./IERC1155Supplyable";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20AdapterContract } from "./IERC20Adapter";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { InitializableContract } from "./Initializable";
import { NativasAdapterContract } from "./NativasAdapter";
import { NativasControlContract } from "./NativasControl";
import { NativasFactoryContract } from "./NativasFactory";
import { NativasHolderContract } from "./NativasHolder";
import { NativasOffsetContract } from "./NativasOffset";
import { NativasTokenContract } from "./NativasToken";
import { OwnableContract } from "./Ownable";
import { OwnableMockContract } from "./OwnableMock";
import { OwnableStubContract } from "./OwnableStub";
import { PausableContract } from "./Pausable";
import { PausableMockContract } from "./PausableMock";
import { PausableStubContract } from "./PausableStub";
import { RolesContract } from "./Roles";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "AccessControlEnumerable"): AccessControlEnumerableContract;
      require(
        name: "AccessControlEnumerableMock"
      ): AccessControlEnumerableMockContract;
      require(
        name: "AccessControlEnumerableStub"
      ): AccessControlEnumerableStubContract;
      require(name: "AccessControlMock"): AccessControlMockContract;
      require(name: "AccessControlStub"): AccessControlStubContract;
      require(name: "ContextMock"): ContextMockContract;
      require(name: "Controllable"): ControllableContract;
      require(name: "ERC1155"): ERC1155Contract;
      require(name: "ERC1155Base"): ERC1155BaseContract;
      require(name: "ERC1155ERC20"): ERC1155ERC20Contract;
      require(name: "ERC1155Offsettable"): ERC1155OffsettableContract;
      require(name: "ERC1155Pausable"): ERC1155PausableContract;
      require(name: "ERC1155Supplyable"): ERC1155SupplyableContract;
      require(name: "ERC1155Swappable"): ERC1155SwappableContract;
      require(name: "ERC1155URIStorable"): ERC1155URIStorableContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC165Mock"): ERC165MockContract;
      require(name: "ERC165Stub"): ERC165StubContract;
      require(name: "IAccessControl"): IAccessControlContract;
      require(
        name: "IAccessControlEnumerable"
      ): IAccessControlEnumerableContract;
      require(name: "IERC1155"): IERC1155Contract;
      require(name: "IERC1155ERC20"): IERC1155ERC20Contract;
      require(name: "IERC1155Holder"): IERC1155HolderContract;
      require(name: "IERC1155Logger"): IERC1155LoggerContract;
      require(name: "IERC1155MetadataURI"): IERC1155MetadataURIContract;
      require(name: "IERC1155Receiver"): IERC1155ReceiverContract;
      require(name: "IERC1155Supplyable"): IERC1155SupplyableContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Adapter"): IERC20AdapterContract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "Initializable"): InitializableContract;
      require(name: "NativasAdapter"): NativasAdapterContract;
      require(name: "NativasControl"): NativasControlContract;
      require(name: "NativasFactory"): NativasFactoryContract;
      require(name: "NativasHolder"): NativasHolderContract;
      require(name: "NativasOffset"): NativasOffsetContract;
      require(name: "NativasToken"): NativasTokenContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "OwnableMock"): OwnableMockContract;
      require(name: "OwnableStub"): OwnableStubContract;
      require(name: "Pausable"): PausableContract;
      require(name: "PausableMock"): PausableMockContract;
      require(name: "PausableStub"): PausableStubContract;
      require(name: "Roles"): RolesContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export {
  AccessControlEnumerableContract,
  AccessControlEnumerableInstance,
} from "./AccessControlEnumerable";
export {
  AccessControlEnumerableMockContract,
  AccessControlEnumerableMockInstance,
} from "./AccessControlEnumerableMock";
export {
  AccessControlEnumerableStubContract,
  AccessControlEnumerableStubInstance,
} from "./AccessControlEnumerableStub";
export {
  AccessControlMockContract,
  AccessControlMockInstance,
} from "./AccessControlMock";
export {
  AccessControlStubContract,
  AccessControlStubInstance,
} from "./AccessControlStub";
export { ContextMockContract, ContextMockInstance } from "./ContextMock";
export { ControllableContract, ControllableInstance } from "./Controllable";
export { ERC1155Contract, ERC1155Instance } from "./ERC1155";
export { ERC1155BaseContract, ERC1155BaseInstance } from "./ERC1155Base";
export { ERC1155ERC20Contract, ERC1155ERC20Instance } from "./ERC1155ERC20";
export {
  ERC1155OffsettableContract,
  ERC1155OffsettableInstance,
} from "./ERC1155Offsettable";
export {
  ERC1155PausableContract,
  ERC1155PausableInstance,
} from "./ERC1155Pausable";
export {
  ERC1155SupplyableContract,
  ERC1155SupplyableInstance,
} from "./ERC1155Supplyable";
export {
  ERC1155SwappableContract,
  ERC1155SwappableInstance,
} from "./ERC1155Swappable";
export {
  ERC1155URIStorableContract,
  ERC1155URIStorableInstance,
} from "./ERC1155URIStorable";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC165MockContract, ERC165MockInstance } from "./ERC165Mock";
export { ERC165StubContract, ERC165StubInstance } from "./ERC165Stub";
export {
  IAccessControlContract,
  IAccessControlInstance,
} from "./IAccessControl";
export {
  IAccessControlEnumerableContract,
  IAccessControlEnumerableInstance,
} from "./IAccessControlEnumerable";
export { IERC1155Contract, IERC1155Instance } from "./IERC1155";
export { IERC1155ERC20Contract, IERC1155ERC20Instance } from "./IERC1155ERC20";
export {
  IERC1155HolderContract,
  IERC1155HolderInstance,
} from "./IERC1155Holder";
export {
  IERC1155LoggerContract,
  IERC1155LoggerInstance,
} from "./IERC1155Logger";
export {
  IERC1155MetadataURIContract,
  IERC1155MetadataURIInstance,
} from "./IERC1155MetadataURI";
export {
  IERC1155ReceiverContract,
  IERC1155ReceiverInstance,
} from "./IERC1155Receiver";
export {
  IERC1155SupplyableContract,
  IERC1155SupplyableInstance,
} from "./IERC1155Supplyable";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { IERC20AdapterContract, IERC20AdapterInstance } from "./IERC20Adapter";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { InitializableContract, InitializableInstance } from "./Initializable";
export {
  NativasAdapterContract,
  NativasAdapterInstance,
} from "./NativasAdapter";
export {
  NativasControlContract,
  NativasControlInstance,
} from "./NativasControl";
export {
  NativasFactoryContract,
  NativasFactoryInstance,
} from "./NativasFactory";
export { NativasHolderContract, NativasHolderInstance } from "./NativasHolder";
export { NativasOffsetContract, NativasOffsetInstance } from "./NativasOffset";
export { NativasTokenContract, NativasTokenInstance } from "./NativasToken";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { OwnableMockContract, OwnableMockInstance } from "./OwnableMock";
export { OwnableStubContract, OwnableStubInstance } from "./OwnableStub";
export { PausableContract, PausableInstance } from "./Pausable";
export { PausableMockContract, PausableMockInstance } from "./PausableMock";
export { PausableStubContract, PausableStubInstance } from "./PausableStub";
export { RolesContract, RolesInstance } from "./Roles";
